# ----------------------
# SERVER CONFIGURATION
# ----------------------
server:
  port: 8080
  servlet:
    context-path: /

# ----------------------
# DATABASE CONFIGURATION
# ----------------------
spring:
  datasource:
    url: jdbc:mysql://${HOST:localhost}:${PORT:3306}/patient?createDatabaseIfNotExist=true
    username: ${USER:root}
    password: ${PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true

  # ----------------------
  # LIQUIBASE CONFIGURATION
  # ----------------------
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: dev,prod

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: = .jsp

# ----------------------
# LOGGING CONFIGURATION
# ----------------------
logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
  file:
    name: logs/patient-application.log

# ----------------------
# SECURITY CONFIGURATION (OPTIONAL)
# ----------------------
security:
  enabled: true

# ----------------------
# OTHER CONFIGURATION
# ----------------------
application:
  name: PatientApplication

#KEY CLOAK
# Keycloak configuration
  keycloak:
    auth-server-url=http://localhost:8080/auth
    realm=your-realm-name
    resource=your-client-id
    public-client=true

