# ----------------------
# SERVER CONFIGURATION
# ----------------------
server:
  port: 8080
  servlet:
    context-path: /api

# ----------------------
# DATABASE CONFIGURATION
# ----------------------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patient?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # ----------------------
  # LIQUIBASE CONFIGURATION
  # ----------------------
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: dev,prod

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: = .jsp

# ----------------------
# LOGGING CONFIGURATION
# ----------------------
logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
  file:
    name: logs/patient-application.log

# ----------------------
# SECURITY CONFIGURATION (OPTIONAL)
# ----------------------
security:
  enabled: true

# ----------------------
# OTHER CONFIGURATION
# ----------------------
application:
  name: PatientApplication


